Itt 573/add banking webhook models
Adyen/adyen-go-api-library pull request #213
Opened 2023-06-06 07:01 UTC by wboereboom

## Summary

## Tested scenarios
No tests as this 

**Fixed issue**:

2023-06-06 14:03 UTC, michaelpaul requested changes

2023-06-06 14:03 UTC, michaelpaul commented on src/adyen/api.go
> +	transferwebhook                    *transferwebhook.NotificationService
These are not actual web services, I don't think they should be added here.

2023-06-06 14:03 UTC, michaelpaul commented on src/transferwebhook/notification_handler.go
> +type NotificationService common.Service
We don't need this type. This package provides mainly a collection of models. The corresponding [service](https://docs.adyen.com/api-explorer/transfers/3/overview) lives in another package. 

Let's rename the file `src/transferwebhook/notification_handler.go` to `src/transferwebhook/webhook_handler.go` and add it to the `.openapi-generator-ignore`.

2023-06-06 14:03 UTC, michaelpaul commented on src/transferwebhook/notification_handler.go
> +type NotificationService common.Service
The same change applies to the other packages.

2023-06-06 14:22 UTC, wboereboom commented on src/adyen/api.go
> +
```suggestion
```

2023-06-08 07:11 UTC, jillingk approved these changes

2023-06-08 13:04 UTC, michaelpaul requested changes

2023-06-08 13:04 UTC, michaelpaul commented on tests/balanceplatform_report_webhooks_handler_test.go
> +		balancePlatformNotification, _ := reportwebhook.HandlereportwebhookRequest(notificationJson)
```suggestion
		balancePlatformNotification, _ := reportwebhook.HandleReportWebhookRequest(notificationJson)
```

2023-06-08 13:04 UTC, michaelpaul commented on src/reportwebhook/model_report_notification_request.go
> +type reportwebhookRequest struct {
This model has an unexported name which doesn't match the filename.  Should be something like:

```suggestion
type ReportWebhookRequest struct {
```

2023-06-08 13:04 UTC, michaelpaul commented on tests/balanceplatform_transfer_webhooks_handler_test.go
> +		balancePlatformNotification, _ := transferwebhook.HandletransferwebhookRequest(notificationJson)
Same issue here, weir name and unexported `transferwebhookRequest` model:
```suggestion
		balancePlatformNotification, _ := transferwebhook.HandleTransferWebhookRequest(notificationJson)
```

2023-06-08 13:04 UTC, michaelpaul commented on src/configurationwebhook/webhook_handler.go
> +func HandleSweepconfigurationwebhookRequest(req string) (*SweepconfigurationwebhookRequest, error) {
Something weird going on with this model's name. Looks like a find and replace took place here. Model names should be the same as in specs.

2023-06-12 09:05 UTC, michaelpaul requested changes
Please remove the `docs` folders. I've added a new badge in the readme which will take users to documentation pages more accurate (after tagging the release)  on https://pkg.go.dev/github.com/adyen/adyen-go-api-library/v7.

2023-06-12 09:05 UTC, michaelpaul commented on src/configurationwebhook/webhook_handler.go
> +func HandleSweepconfigurationNotificationRequest(req string) (*SweepConfigurationNotificationRequest, error) {
```suggestion
func HandleSweepConfigurationNotificationRequest(req string) (*SweepConfigurationNotificationRequest, error) {
```

2023-06-12 09:05 UTC, michaelpaul commented on src/platformsnotificationevents/model_refund_funds_transfer_notification.go
> +type RefundFundstransferwebhook struct {
I would rather to leave these old AFP models unchanged since they are "deprecated".

2023-06-12 09:05 UTC, michaelpaul commented on src/reportwebhook/client.go
> +	// API Services
Let's remove this file since this is not an API service.

2023-06-12 09:05 UTC, michaelpaul commented on src/reportwebhook/webhook_handler.go
> +func HandleReportwebhookRequest(req string) (*ReportNotificationRequest, error) {
```suggestion
// HandleReportNotificationRequest creates a Notification object from the given JSON string
func HandleReportNotificationRequest(req string) (*ReportNotificationRequest, error) {
```

2023-06-12 09:05 UTC, michaelpaul commented on src/transferwebhook/client.go
> +	// API Services
This file is not necessary.

2023-06-12 09:05 UTC, michaelpaul commented on src/transferwebhook/webhook_handler.go
> +func HandleTransferwebhookRequest(req string) (*TransferNotificationRequest, error) {
```suggestion
// HandleTransferNotificationRequest creates a Notification object from the given JSON string
func HandleTransferNotificationRequest(req string) (*TransferNotificationRequest, error) {
```

2023-06-13 07:08 UTC, wboereboom commented on src/platformsnotificationevents/model_refund_funds_transfer_notification.go
> +type RefundFundstransferwebhook struct {
reverted these changes

2023-06-13 07:33 UTC, michaelpaul approved these changes

2023-06-13 07:33 UTC, merged